<?php
/**
 * @author MageMoto Team
 * @copyright Copyright (c) 2020 MageMoto (https://www.magemoto.com)
 * @package MageMoto_Base
 */
?>
<?php
/**
 * @var \Magento\Backend\Block\Template $block
 */
?>
<script>
    require([
        "jquery"
    ], function($){
        $(document).ready(function () {
            $('a[href*="https://mavenbird.com"], a[href*="http://mavenbird.com"], a[href*="https://marketplace.magento.com"]')
                .attr('target', '_blank');
        });
    });
</script>
